name: Fetch Federal Registrar Data

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute federal_registrar script
        run: |
          python federal_register_api.py $(date +"%Y-%m-%d")
      
      - name: store output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Exec orders identified and stores