name: Fetch Federal Registrar Data

on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/download-artifact@v4
      - name: execute federal_registrar script
        run: |
          python federal_register_api.py
